"""Pytest configuration and fixtures for coop_pilot stack tests."""

import os
from pathlib import Path

import pytest
from dotenv import load_dotenv

# Load environment from data/.env (generated by scripts/gen-env.sh)
load_dotenv(Path(__file__).resolve().parents[2] / "data" / ".env")


@pytest.fixture(scope="session")
def env_config():
    """Load and return environment configuration."""
    return {
        "mqtt_host": os.getenv("MQTT_HOST", "localhost"),
        "mqtt_port": int(os.getenv("MOSQUITTO_MQTTS_PORT", "8883")),
        "mqtt_port_internal": 1883,
        "mqtt_health_user": os.getenv("MOSQUITTO_HEALTH_USER", "health"),
        "mqtt_health_password": os.getenv("MOSQUITTO_HEALTH_PASSWORD", "health"),
        "chirpstack_mqtt_user": os.getenv("CHIRPSTACK_MQTT_USERNAME", "chirpstack"),
        "chirpstack_mqtt_password": os.getenv("CHIRPSTACK_MQTT_PASSWORD", "chirpstack"),
        "frigate_mqtt_password": os.getenv("FRIGATE_MQTT_PASSWORD", "frigate"),
        "chirpstack_api_url": f"http://localhost:{os.getenv('CHIRPSTACK_UI_PORT', '8080')}",
        "chirpstack_rest_url": f"http://localhost:{os.getenv('CHIRPSTACK_REST_PORT', '8090')}",
        "chirpstack_pg_user": os.getenv("CHIRPSTACK_PG_USER", "chirpstack"),
        "frigate_url": f"http://localhost:{os.getenv('FRIGATE_PORT', '8971')}",
    }


@pytest.fixture(scope="session")
def docker_client():
    """Create Docker client for container operations."""
    import docker
    return docker.from_env()


@pytest.fixture(scope="session")
def expected_containers():
    """List of expected container names."""
    return [
        "coop-mosquitto",
        "coop-cs-postgres",
        "coop-cs-redis",
        "coop-chirpstack",
        "coop-cs-gwbridge",
        "coop-cs-rest",
        "coop-frigate",
    ]


@pytest.fixture(scope="session")
def container_names():
    """Named coop_pilot service containers from docker-compose.coop.yml."""
    return {
        "mosquitto": "coop-mosquitto",
        "chirpstack_postgres": "coop-cs-postgres",
        "redis": "coop-cs-redis",
        "chirpstack": "coop-chirpstack",
        "chirpstack_gateway_bridge": "coop-cs-gwbridge",
        "chirpstack_rest": "coop-cs-rest",
        "frigate": "coop-frigate",
    }
