#!/usr/bin/env bash
# Run docker compose with PUID/PGID set dynamically from the current user.
# APP_ENV selects the compose overlay (prod|dev|test). Default: prod.
# Environment is loaded from data/.env (generated by scripts/gen-env.sh).
#
# Usage:
#   ./scripts/compose.sh up -d
#   APP_ENV=dev  ./scripts/compose.sh up -d
#   APP_ENV=test ./scripts/compose.sh up -d
#   ./scripts/compose.sh logs -f

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# PUID/PGID set dynamically — do not store in data/.env
export PUID=$(id -u)
export PGID=$(id -g)

COMPOSE_FILES=(-f "$ROOT_DIR/docker/docker-compose.coop.yml")

# --project-directory ensures relative paths in the compose file resolve from
# the project root, not from docker/. --env-file loads secrets from data/.env.
exec docker compose \
  --project-directory "$ROOT_DIR" \
  --env-file "$ROOT_DIR/data/.env" \
  "${COMPOSE_FILES[@]}" \
  "$@"
